name: 98 - Copy Issues to Project

env:
  GH_TOKEN: ${{ github.token }}

on:
  workflow_dispatch:
jobs:

  copyIssuesToProject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
